ALTER TABLE message ADD COLUMN IF NOT EXISTS letter_type VARCHAR(20) DEFAULT 'private';
ALTER TABLE message ADD COLUMN IF NOT EXISTS moderation_status VARCHAR(20) DEFAULT 'approved';
ALTER TABLE message ADD COLUMN IF NOT EXISTS original_receiver_type VARCHAR(20);
ALTER TABLE message ADD COLUMN IF NOT EXISTS rejection_reason TEXT;
ALTER TABLE message ADD COLUMN IF NOT EXISTS town VARCHAR(50);
ALTER TABLE message ADD COLUMN IF NOT EXISTS village VARCHAR(50);
