CREATE SEQUENCE IF NOT EXISTS ai_feedback_id_seq AS BIGINT OWNED BY ai_feedback.id;
ALTER TABLE ai_feedback ALTER COLUMN id SET DEFAULT nextval('ai_feedback_id_seq');
SELECT setval('ai_feedback_id_seq', COALESCE((SELECT max(id) FROM ai_feedback), 1), COALESCE((SELECT max(id) FROM ai_feedback), 1) IS NOT NULL);
CREATE SEQUENCE IF NOT EXISTS ai_knowledge_id_seq AS BIGINT OWNED BY ai_knowledge.id;
ALTER TABLE ai_knowledge ALTER COLUMN id SET DEFAULT nextval('ai_knowledge_id_seq');
SELECT setval('ai_knowledge_id_seq', COALESCE((SELECT max(id) FROM ai_knowledge), 1), COALESCE((SELECT max(id) FROM ai_knowledge), 1) IS NOT NULL);
CREATE SEQUENCE IF NOT EXISTS blocked_email_id_seq AS BIGINT OWNED BY blocked_email.id;
ALTER TABLE blocked_email ALTER COLUMN id SET DEFAULT nextval('blocked_email_id_seq');
SELECT setval('blocked_email_id_seq', COALESCE((SELECT max(id) FROM blocked_email), 1), COALESCE((SELECT max(id) FROM blocked_email), 1) IS NOT NULL);
CREATE SEQUENCE IF NOT EXISTS chat_message_id_seq AS BIGINT OWNED BY chat_message.id;
ALTER TABLE chat_message ALTER COLUMN id SET DEFAULT nextval('chat_message_id_seq');
SELECT setval('chat_message_id_seq', COALESCE((SELECT max(id) FROM chat_message), 1), COALESCE((SELECT max(id) FROM chat_message), 1) IS NOT NULL);
CREATE SEQUENCE IF NOT EXISTS chat_room_id_seq AS BIGINT OWNED BY chat_room.id;
ALTER TABLE chat_room ALTER COLUMN id SET DEFAULT nextval('chat_room_id_seq');
SELECT setval('chat_room_id_seq', COALESCE((SELECT max(id) FROM chat_room), 1), COALESCE((SELECT max(id) FROM chat_room), 1) IS NOT NULL);
CREATE SEQUENCE IF NOT EXISTS comment_id_seq AS BIGINT OWNED BY comment.id;
ALTER TABLE comment ALTER COLUMN id SET DEFAULT nextval('comment_id_seq');
SELECT setval('comment_id_seq', COALESCE((SELECT max(id) FROM comment), 1), COALESCE((SELECT max(id) FROM comment), 1) IS NOT NULL);
CREATE SEQUENCE IF NOT EXISTS friend_group_id_seq AS BIGINT OWNED BY friend_group.id;
ALTER TABLE friend_group ALTER COLUMN id SET DEFAULT nextval('friend_group_id_seq');
SELECT setval('friend_group_id_seq', COALESCE((SELECT max(id) FROM friend_group), 1), COALESCE((SELECT max(id) FROM friend_group), 1) IS NOT NULL);
CREATE SEQUENCE IF NOT EXISTS google_calendar_config_id_seq AS BIGINT OWNED BY google_calendar_config.id;
ALTER TABLE google_calendar_config ALTER COLUMN id SET DEFAULT nextval('google_calendar_config_id_seq');
SELECT setval('google_calendar_config_id_seq', COALESCE((SELECT max(id) FROM google_calendar_config), 1), COALESCE((SELECT max(id) FROM google_calendar_config), 1) IS NOT NULL);
CREATE SEQUENCE IF NOT EXISTS gps_calibration_id_seq AS BIGINT OWNED BY gps_calibration.id;
ALTER TABLE gps_calibration ALTER COLUMN id SET DEFAULT nextval('gps_calibration_id_seq');
SELECT setval('gps_calibration_id_seq', COALESCE((SELECT max(id) FROM gps_calibration), 1), COALESCE((SELECT max(id) FROM gps_calibration), 1) IS NOT NULL);
CREATE SEQUENCE IF NOT EXISTS heritage_stamp_id_seq AS BIGINT OWNED BY heritage_stamp.id;
ALTER TABLE heritage_stamp ALTER COLUMN id SET DEFAULT nextval('heritage_stamp_id_seq');
SELECT setval('heritage_stamp_id_seq', COALESCE((SELECT max(id) FROM heritage_stamp), 1), COALESCE((SELECT max(id) FROM heritage_stamp), 1) IS NOT NULL);
CREATE SEQUENCE IF NOT EXISTS lawyer_schedule_id_seq AS BIGINT OWNED BY lawyer_schedule.id;
ALTER TABLE lawyer_schedule ALTER COLUMN id SET DEFAULT nextval('lawyer_schedule_id_seq');
SELECT setval('lawyer_schedule_id_seq', COALESCE((SELECT max(id) FROM lawyer_schedule), 1), COALESCE((SELECT max(id) FROM lawyer_schedule), 1) IS NOT NULL);
CREATE SEQUENCE IF NOT EXISTS legal_appointment_id_seq AS BIGINT OWNED BY legal_appointment.id;
ALTER TABLE legal_appointment ALTER COLUMN id SET DEFAULT nextval('legal_appointment_id_seq');
SELECT setval('legal_appointment_id_seq', COALESCE((SELECT max(id) FROM legal_appointment), 1), COALESCE((SELECT max(id) FROM legal_appointment), 1) IS NOT NULL);
CREATE SEQUENCE IF NOT EXISTS legal_post_id_seq AS BIGINT OWNED BY legal_post.id;
ALTER TABLE legal_post ALTER COLUMN id SET DEFAULT nextval('legal_post_id_seq');
SELECT setval('legal_post_id_seq', COALESCE((SELECT max(id) FROM legal_post), 1), COALESCE((SELECT max(id) FROM legal_post), 1) IS NOT NULL);
CREATE SEQUENCE IF NOT EXISTS news_comment_id_seq AS BIGINT OWNED BY news_comment.id;
ALTER TABLE news_comment ALTER COLUMN id SET DEFAULT nextval('news_comment_id_seq');
SELECT setval('news_comment_id_seq', COALESCE((SELECT max(id) FROM news_comment), 1), COALESCE((SELECT max(id) FROM news_comment), 1) IS NOT NULL);
CREATE SEQUENCE IF NOT EXISTS news_recommendation_id_seq AS BIGINT OWNED BY news_recommendation.id;
ALTER TABLE news_recommendation ALTER COLUMN id SET DEFAULT nextval('news_recommendation_id_seq');
SELECT setval('news_recommendation_id_seq', COALESCE((SELECT max(id) FROM news_recommendation), 1), COALESCE((SELECT max(id) FROM news_recommendation), 1) IS NOT NULL);
CREATE SEQUENCE IF NOT EXISTS news_vote_id_seq AS BIGINT OWNED BY news_vote.id;
ALTER TABLE news_vote ALTER COLUMN id SET DEFAULT nextval('news_vote_id_seq');
SELECT setval('news_vote_id_seq', COALESCE((SELECT max(id) FROM news_vote), 1), COALESCE((SELECT max(id) FROM news_vote), 1) IS NOT NULL);
CREATE SEQUENCE IF NOT EXISTS post_vote_id_seq AS BIGINT OWNED BY post_vote.id;
ALTER TABLE post_vote ALTER COLUMN id SET DEFAULT nextval('post_vote_id_seq');
SELECT setval('post_vote_id_seq', COALESCE((SELECT max(id) FROM post_vote), 1), COALESCE((SELECT max(id) FROM post_vote), 1) IS NOT NULL);
CREATE SEQUENCE IF NOT EXISTS psycho_appointment_id_seq AS BIGINT OWNED BY psycho_appointment.id;
ALTER TABLE psycho_appointment ALTER COLUMN id SET DEFAULT nextval('psycho_appointment_id_seq');
SELECT setval('psycho_appointment_id_seq', COALESCE((SELECT max(id) FROM psycho_appointment), 1), COALESCE((SELECT max(id) FROM psycho_appointment), 1) IS NOT NULL);
CREATE SEQUENCE IF NOT EXISTS psycho_doctor_schedule_id_seq AS BIGINT OWNED BY psycho_doctor_schedule.id;
ALTER TABLE psycho_doctor_schedule ALTER COLUMN id SET DEFAULT nextval('psycho_doctor_schedule_id_seq');
SELECT setval('psycho_doctor_schedule_id_seq', COALESCE((SELECT max(id) FROM psycho_doctor_schedule), 1), COALESCE((SELECT max(id) FROM psycho_doctor_schedule), 1) IS NOT NULL);
CREATE SEQUENCE IF NOT EXISTS psycho_google_calendar_config_id_seq AS BIGINT OWNED BY psycho_google_calendar_config.id;
ALTER TABLE psycho_google_calendar_config ALTER COLUMN id SET DEFAULT nextval('psycho_google_calendar_config_id_seq');
SELECT setval('psycho_google_calendar_config_id_seq', COALESCE((SELECT max(id) FROM psycho_google_calendar_config), 1), COALESCE((SELECT max(id) FROM psycho_google_calendar_config), 1) IS NOT NULL);
CREATE SEQUENCE IF NOT EXISTS psycho_post_id_seq AS BIGINT OWNED BY psycho_post.id;
ALTER TABLE psycho_post ALTER COLUMN id SET DEFAULT nextval('psycho_post_id_seq');
SELECT setval('psycho_post_id_seq', COALESCE((SELECT max(id) FROM psycho_post), 1), COALESCE((SELECT max(id) FROM psycho_post), 1) IS NOT NULL);
CREATE SEQUENCE IF NOT EXISTS push_subscription_id_seq AS BIGINT OWNED BY push_subscription.id;
ALTER TABLE push_subscription ALTER COLUMN id SET DEFAULT nextval('push_subscription_id_seq');
SELECT setval('push_subscription_id_seq', COALESCE((SELECT max(id) FROM push_subscription), 1), COALESCE((SELECT max(id) FROM push_subscription), 1) IS NOT NULL);
CREATE SEQUENCE IF NOT EXISTS share_comment_id_seq AS BIGINT OWNED BY share_comment.id;
ALTER TABLE share_comment ALTER COLUMN id SET DEFAULT nextval('share_comment_id_seq');
SELECT setval('share_comment_id_seq', COALESCE((SELECT max(id) FROM share_comment), 1), COALESCE((SELECT max(id) FROM share_comment), 1) IS NOT NULL);
CREATE SEQUENCE IF NOT EXISTS shared_route_id_seq AS BIGINT OWNED BY shared_route.id;
ALTER TABLE shared_route ALTER COLUMN id SET DEFAULT nextval('shared_route_id_seq');
SELECT setval('shared_route_id_seq', COALESCE((SELECT max(id) FROM shared_route), 1), COALESCE((SELECT max(id) FROM shared_route), 1) IS NOT NULL);
CREATE SEQUENCE IF NOT EXISTS store_info_id_seq AS BIGINT OWNED BY store_info.id;
ALTER TABLE store_info ALTER COLUMN id SET DEFAULT nextval('store_info_id_seq');
SELECT setval('store_info_id_seq', COALESCE((SELECT max(id) FROM store_info), 1), COALESCE((SELECT max(id) FROM store_info), 1) IS NOT NULL);
CREATE SEQUENCE IF NOT EXISTS tong_bot_draft_id_seq AS BIGINT OWNED BY tong_bot_draft.id;
ALTER TABLE tong_bot_draft ALTER COLUMN id SET DEFAULT nextval('tong_bot_draft_id_seq');
SELECT setval('tong_bot_draft_id_seq', COALESCE((SELECT max(id) FROM tong_bot_draft), 1), COALESCE((SELECT max(id) FROM tong_bot_draft), 1) IS NOT NULL);
CREATE SEQUENCE IF NOT EXISTS village_alert_id_seq AS BIGINT OWNED BY village_alert.id;
ALTER TABLE village_alert ALTER COLUMN id SET DEFAULT nextval('village_alert_id_seq');
SELECT setval('village_alert_id_seq', COALESCE((SELECT max(id) FROM village_alert), 1), COALESCE((SELECT max(id) FROM village_alert), 1) IS NOT NULL);
CREATE SEQUENCE IF NOT EXISTS village_cache_id_seq AS BIGINT OWNED BY village_cache.id;
ALTER TABLE village_cache ALTER COLUMN id SET DEFAULT nextval('village_cache_id_seq');
SELECT setval('village_cache_id_seq', COALESCE((SELECT max(id) FROM village_cache), 1), COALESCE((SELECT max(id) FROM village_cache), 1) IS NOT NULL);
CREATE SEQUENCE IF NOT EXISTS village_event_id_seq AS BIGINT OWNED BY village_event.id;
ALTER TABLE village_event ALTER COLUMN id SET DEFAULT nextval('village_event_id_seq');
SELECT setval('village_event_id_seq', COALESCE((SELECT max(id) FROM village_event), 1), COALESCE((SELECT max(id) FROM village_event), 1) IS NOT NULL);
CREATE SEQUENCE IF NOT EXISTS village_event_attendee_id_seq AS BIGINT OWNED BY village_event_attendee.id;
ALTER TABLE village_event_attendee ALTER COLUMN id SET DEFAULT nextval('village_event_attendee_id_seq');
SELECT setval('village_event_attendee_id_seq', COALESCE((SELECT max(id) FROM village_event_attendee), 1), COALESCE((SELECT max(id) FROM village_event_attendee), 1) IS NOT NULL);
CREATE SEQUENCE IF NOT EXISTS village_event_chat_id_seq AS BIGINT OWNED BY village_event_chat.id;
ALTER TABLE village_event_chat ALTER COLUMN id SET DEFAULT nextval('village_event_chat_id_seq');
SELECT setval('village_event_chat_id_seq', COALESCE((SELECT max(id) FROM village_event_chat), 1), COALESCE((SELECT max(id) FROM village_event_chat), 1) IS NOT NULL);
CREATE SEQUENCE IF NOT EXISTS village_page_id_seq AS BIGINT OWNED BY village_page.id;
ALTER TABLE village_page ALTER COLUMN id SET DEFAULT nextval('village_page_id_seq');
SELECT setval('village_page_id_seq', COALESCE((SELECT max(id) FROM village_page), 1), COALESCE((SELECT max(id) FROM village_page), 1) IS NOT NULL);
CREATE SEQUENCE IF NOT EXISTS village_wish_id_seq AS BIGINT OWNED BY village_wish.id;
ALTER TABLE village_wish ALTER COLUMN id SET DEFAULT nextval('village_wish_id_seq');
SELECT setval('village_wish_id_seq', COALESCE((SELECT max(id) FROM village_wish), 1), COALESCE((SELECT max(id) FROM village_wish), 1) IS NOT NULL);
